apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: default
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
      - name: homer
        image: samsja/homer:0.1.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /www/assets/config.yml
            subPath: config.yml
            name: "config"

      volumes:
        - name: "config"
          configMap:
            name: "homer-config"
